######################################################################
# Automatically generated by qmake (3.1) Sat Nov 22 22:46:34 2025
######################################################################

TEMPLATE = app
TARGET = test
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_UP_TO=0x060000 # disables all APIs deprecated in Qt 6.0.0 and earlier

# Input
HEADERS += include/audio/audio_engine.h \
           include/audio/jitter_buffer.h \
           include/audio/opus_codec.h \
           include/common/lock_free_queue.h \
           include/common/result.h \
           include/common/types.h \
           include/network/udp_socket.h \
           include/network/websocket_client.h \
           include/protocol/control_messages.h \
           include/session/voice_session.h \
           include/ui/login_dialog.h \
           include/ui/main_window.h
SOURCES += test_qt.cpp \
           /test_qt.cpp \
           examples/network_test.cpp \
           examples/voice_loopback_demo.cpp \
           src/main.cpp \
           src/ui_main.cpp \
           build/voip-client_autogen/mocs_compilation_Debug.cpp \
           src/audio/audio_engine.cpp \
           src/audio/jitter_buffer.cpp \
           src/audio/opus_codec.cpp \
           src/common/result.cpp \
           src/network/udp_socket.cpp \
           src/network/websocket_client.cpp \
           src/session/voice_session.cpp \
           src/ui/login_dialog.cpp \
           src/ui/main_window.cpp \
           tests/audio/test_jitter_buffer.cpp \
           tests/audio/test_opus_codec.cpp \
           tests/integration/test_audio_loopback.cpp \
           build/voip-client_autogen/3YJK5W5UP7_Debug/qrc_resources.cpp \
           build/CMakeFiles/4.1.1/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           build/voip-client_autogen/include_Debug/3YJK5W5UP7/qrc_resources_CMAKE_.cpp
RESOURCES += resources/resources.qrc
